# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """\
$time\
$all\
$character"""

[fill]
symbol = " "

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "

[package]
disabled = true

[character]
success_symbol = "[  ](bold bright-green)"
error_symbol = "[  ](bold red)"

[time]
style = "bold yellow"
time_format = "%H:%M"
format = "[$time]($style) "
disabled = false

[aws]
disabled = true

[custom]
[custom.env_slug]
disabled = false
description = "Display ENVIRONMENT_SLUG if set and notify if "
when = """[[ $(git ls-remote --get-url) =~ gitlab.com:alcemy ]] && [[ -f $(git rev-parse --show-toplevel)/.env ]]"""
format = "(in [$symbol($output )]($style))"
style = "bold red"
command = """
SYMBOL=""
GIT_ROOT=$(git rev-parse --show-toplevel)
DYN_ENV=$(git branch --show-current | cut -s -d '+' -f 2)
ENV_SLUG=$(sed -n 's/^ENVIRONMENT_SLUG=\\([^#]*\\).*$/\\1/p' $GIT_ROOT/.env | tail -n1)

[[ -z $DYN_ENV ]] && [[ $ENV_SLUG == "testing" ]] && exit

[[ -z $DYN_ENV ]] && [[ $ENV_SLUG =~ ^dyn_ ]] && SYMBOL="🚧 mismatch "
[[ -n $DYN_ENV ]] && [[ "dyn_$DYN_ENV" != $ENV_SLUG ]] && SYMBOL="🚧 mismatch "

[[ -z $ENV_SLUG ]] && ENV_SLUG="<undefined env slug>"

[[ $ENV_SLUG =~ ^prod ]] && SYMBOL="🛑 $SYMBOL" && ENV_SLUG=${ENV_SLUG^^}

echo "${SYMBOL}${ENV_SLUG}"
"""
shell = ["bash", "--noprofile", "--norc"]
